name: Core build

on: 
  push:
  workflow_dispatch:

jobs:
  build-version-test:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - run: |
        dir c:\
        dir d:\
        dir D:\a
        dir D:\a\runner
        dir D:\a\runner\runner
        dotnet --version
        dotnet --info
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
      env:
        DOTNET_INSTALL_DIR: /users/runner/alternate/dotnet
    - name: Create Certificate
      run: |
        dotnet dev-certs https --clean
        dotnet dev-certs https -ep src/PlaywrightSharp.TestServer/testCert.cer
#  build-version-test-no-multilevel:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/setup-dotnet@main
#      with:
#        dotnet-version: '2.1.802'
#    - name: info
#      run: |
#        dotnet --version
#        dotnet --info
#      env:
#        DOTNET_MULTILEVEL_LOOKUP: 0
#  build:
#    name: ${{ matrix.runs-on }}
#    runs-on: ${{ matrix.runs-on }}
#    strategy:
#      fail-fast: false
#      matrix:
#        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
#    
#    steps:
#    - uses: actions/setup-dotnet@main
#    - name: check dotnet version early
#      run: |
#        dotnet --info
#        dotnet --list-sdks
#        dotnet --list-runtimes
#        echo %DOTNET_ROOT%
#        echo %PATH%
#        echo $DOTNET_ROOT
#        echo $PATH
#    - name: Setup .NET Core with global.json
#      uses: actions/setup-dotnet@fix171
#      with:
#        dotnet-version: 3.0
#    - name: check dotnet version late
#      run: |
#        dotnet --info
#        dotnet --list-sdks
#        dotnet --list-runtimes
#        echo %DOTNET_ROOT%
#        echo %PATH%
#        echo $DOTNET_ROOT
#        echo $PATH
#    - name: build with dotnet
#      run: |
#        ls
#        pwd
#        dotnet build setup-dotnet-test.sln
#        dotnet test setup-dotnet-test.sln
#        dotnet run --project test-standard/test-standard.csproj 
#        dotnet run --project test-tests/test-tests.csproj 
