name: Core build

on: [push]

jobs:
  build:
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-10.14, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: check dotnet version early
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes
        echo %DOTNET_ROOT%
        echo %PATH%
        echo $DOTNET_ROOT
        echo $PATH
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100
    - name: check dotnet version late
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes
        echo %DOTNET_ROOT%
        echo %PATH%
        echo $DOTNET_ROOT
        echo $PATH
    - name: build with dotnet
      run: |
        set DOTNET_ROOT=%DOTNET_ROOT%3.0.100/x64
        DOTNET_ROOT=$DOTNET_ROOT/3.0.100/x64
        dotnet build
        dotnet test
        dotnet run --project test-standard/test-standard.csproj 
        dotnet run --project test-tests/test-tests.csproj 
