name: Core build

on: [push]

jobs:
#  build-version-test:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/setup-dotnet@master
#      with:
#        dotnet-version: '2.1.802'
#    - run: |
#        dotnet --version
#        dotnet --info
#  build-version-test-no-multilevel:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/setup-dotnet@master
#      with:
#        dotnet-version: '2.1.802'
#    - name: info
#      run: |
#        dotnet --version
#        dotnet --info
#      env:
#        DOTNET_MULTILEVEL_LOOKUP: 0
  build:
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
#    env:
#      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    strategy:
      fail-fast: false
      matrix:
#        runs-on: [macOS-10.14, windows-2016, ubuntu-latest, windows-latest]
        runs-on: [macOS-10.14, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: check dotnet version early
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes
        echo %DOTNET_ROOT%
        echo %PATH%
        echo $DOTNET_ROOT
        echo $PATH
    - name: Setup .NET Core
      uses: actions/setup-dotnet@c0e4e5bdd4051f081e9d1cc4a9832719aba3e3e5
      with:
        dotnet-version: 3.0.100-preview8-013656
    - name: check dotnet version late
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes
        echo %DOTNET_ROOT%
        echo %PATH%
        echo $DOTNET_ROOT
        echo $PATH
    - name: build with dotnet
      run: |
        dotnet build
        dotnet test
        dotnet run --project test-standard/test-standard.csproj 
        dotnet run --project test-tests/test-tests.csproj 
