name: Core build

on: [push]

jobs:
  build:
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-10.14, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: check dotnet version early
      run: dotnet --list-sdks
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet --list-sdks
